<a href="https://colab.research.google.com/github/sauradip007/Churning_ANN/blob/master/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing the libraries

# Artificial Neural Network

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

In [3]:
tf.__version__

'2.8.2'

### Importing the dataset

In [11]:
df = pd.read_csv('Churn_Modelling.csv')

In [12]:
df.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [13]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [14]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [15]:
print(y)

[1 0 1 ... 1 1 0]


In [16]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

### Encoding categorical data

In [17]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [18]:
from sklearn import preprocessing

In [19]:
le = preprocessing.LabelEncoder()

Label Encoding the "Gender" column

In [20]:
X[:,2] = le.fit_transform(X[:,2])

In [21]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [22]:
 from sklearn.preprocessing import OneHotEncoder

In [23]:
enc = OneHotEncoder()

In [24]:
from sklearn.compose import ColumnTransformer

In [25]:
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [26]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [27]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Splitting the dataset into the Training set and Test set

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
X_train.shape

(8000, 12)

In [33]:
y_train.shape

(8000,)

### Initializing the ANN

In [34]:
ann = tf.keras.models.Sequential()

In [35]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the input layer and the first hidden layer

In [36]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

### Adding the output layer

In [37]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [38]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy',metrics =[['accuracy']])

### Training the ANN on the Training set

In [39]:
ann.fit(X_train,y_train, epochs = 120)

Epoch 1/120
250/250 [==============================] - 1s 1ms/step - loss: 0.5191 - accuracy: 0.7843
Epoch 2/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4596 - accuracy: 0.7960
Epoch 3/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4456 - accuracy: 0.7960
Epoch 4/120
250/250 [==============================] - 0s 993us/step - loss: 0.4380 - accuracy: 0.7960
Epoch 5/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4337 - accuracy: 0.7960
Epoch 6/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4301 - accuracy: 0.7979
Epoch 7/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4264 - accuracy: 0.8034
Epoch 8/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4228 - accuracy: 0.8089
Epoch 9/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4184 - accuracy: 0.8142
Epoch 10/120
250/250 [==============================] - 0s 1ms/step - loss: 0.4137 - accu

## Part 4 - Making the predictions and evaluating the model

In [40]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [41]:
print(ann.predict(scaler.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))
# very low chance they will leave the bank

[[0.02476504]]


### Predicting the Test set results

In [42]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [44]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))

[[1515  206]
 [  80  199]]
0.857
